apiVersion: v1
kind: Service
metadata:
  name: texlm-service
  namespace: texlm-system
spec:
  type: NodePort
  selector:
    app: texlm
  ports:
    - protocol: TCP
      port: 8501        # port within cluster
      targetPort: 8501  # port within pod
      nodePort: 32000   # port for access